---
name: Create a release
on:
  push:
    tags:
      - "v*.*.*" # Specify tag pattern for releases, e.g., v1.0.0
env:
  IMAGE_NAME: micropulse
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: "checkout@v4"
      - name: Create Release
        id: create_release
        uses: "create-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
